name: Pipeline

on:
  workflow_dispatch:
  schedule:              # scheduleは main branchのみで動作
    - cron: '30 2 * * *' # 毎日深夜 2:30 に実行
env:
  TZ: "Asia/Tokyo"

jobs:
  fetch:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10.13

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create download folder name on date
      run: |
        folder_name='.docs/fixed/$(date +'%Y%m%d-%H%m%S')
        mkdir folder_name
        echo "FOLDER_NAME=$folder_name" >> $GITHUB_ENV
      id: create_folder

    # - name: Download the Open Data
    #   run: python download.py ${{env.FOLDER_NAME}}

    - name: Run pipeline
      # run: python datanorm.py ./docs/source
      run: python pipeline_executor.py ${{env.FOLDER_NAME}}

    - name: Upload to the Google Drive
      uses: adityak74/google-drive-upload-git-action@main
      with:
        credentials: ${{ secrets.GDRIVE_CREDENTIAL }}
        # filename: "./docs/fixed/*"
        filename: ${{env.FOLDER_NAME}}
        folderId: ${{ secrets.GDRIVE_FOLDERID }}
        overwrite: "true" # optional boolean
    
    # - name: Create report page
    
    - name: Publish to the GitHub Pags
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
        publish_branch: gh-pages
        enable_jekyll: true
        allow_empty_commit: true
        keep_files: false
